baseURL = 'https://sheepitm.koolkid6958.dev/'
languageCode = 'en-us'
title = 'Sheepit-Manager'
theme = 'hextra'

# Allow html in the .md files
[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
name = "Docs"
pageRef = "/docs"

[[menu.main]]
name = "Install"
pageRef = "/docs/installation"
